class AutoFlashError(Exception): ...
class FileNotSupportedError(AutoFlashError): ...
class ApiError(AutoFlashError): ...
class CardNotFoundError(AutoFlashError): ...
class StorageError(AutoFlashError): ...
